@startuml GbDoc_GbStandardPrefix
/'
Diagram:        GbDoc_GbStandardPrefix
DateCreate:     23/08/2018
Description:    This is where we keep the Metanorma GbDoc model definitions.
                The GbDoc format is an instance of the Metanorma IsoDoc model.
                Details of the parent model can be found on its page.

Hystory of changes:
> 31/08/2018
    - Enumeration type GbStandardSocialPrefix has been updated. plus sign as a prefix has been removed from all items in the enumeration
'/

'******* CONFIGURATION ************************************************
skinparam classAttributeIconSize 0
skinparam Dpi 150
skinparam Monochrome true
skinparam LineType ortho
skinparam nodesep 10
skinparam ranksep 30
hide circle
/' skinparam CircledCharacterRadius 0 '/
/' skinparam CircledCharacterFontSize 0 '/
skinparam Default {
TextAlignment center
FontName Helvetica
}
skinparam Class {
AttributeIconSize 0
BackgroundColor White
FontStyle bold
StereotypeFontSize 10
}
skinparam Rectangle {
BackgroundColor White
FontStyle bold
FontSize 11
StereotypeFontSize 10
}
skinparam Object {
BackgroundColor White
FontStyle bold
FontSize 11
StereotypeFontSize 10
}

skinparam Entity {
StereotypeFontSize 10
}

'******* CLASS DEFINITION *********************************************
class GbStandardPrefix {

}

enum GbStandardNationalPrefix <<enumeration>>{
    GB_national
    GBn_confidential
    GJB_military
    GSB_physical
}

enum GbStandardSectorPrefix <<enumeration>>{
    NY_agriculture
    SC_aquatic
    SL_water_resources
    QB_light_industry
    FZ_textile
    YY_medicine
    MZ_civil_affairs
    JY_education
    YC_tobacco
    YB_ferrous_metallurgy
    YS_nonferrous_metallurgy
    SY_natural_gas
    HG_chemical_industry
    SH_petrochemical
    JC_building_materials
    DZ_geological
    TD_land_management
    CH_surveying
    JB_mechanical
    QC_automotive
    MN_civil_aviation
    WJ_ordnance
    CB_ships
    HB_aviation
    QJ_aerospace
    EJ_nuclear_industry
    TB_rail_transport
    JT_traffic
    LD_work_safety
    SJ_electronics
    YD_communication
    GY_media
    DL_electricity
    JR_financial
    HY_oceanic
    DA_archiving
    SN_inspection
    WH_culture
    TY_sports
    SB_business
    WB_materials_management
    HJ_environment_protection
    XB_rare_earth
    CJ_town_construction
    JG_construction_industry
    CY_news_publishing
    MT_coal
    WS_health
    GA_public_safety
    BB_packaging
    DB_seismology
    LB_tourism
    QX_meteorological
    WM_foreign_trade
    HS_customs
    YZ_postal
    GM_cryptography
    AQ_production_safety
    GH_supply_marketing
    LS_food
    TJ_railway_traffic
    ZY_chinese_medicine
    LY_forestry
}

enum GbStandardProfessionalPrefix <<enumeration>>{
    ZB_categorycode
}

enum GbStandardLocalPrefix <<enumeration>>{
    DBXX
}

enum GbStandardEnterprisePrefix <<enumeration>>{
    Q
}

enum GbStandardSocialPrefix <<enumeration>>{
    prefix: String = "T"
    groupCode: Character[3] = "XXX"
}

'******* NOTES ********************************************************
note bottom of GbStandardNationalPrefix: If a GbStandardNationalPrefix\nor GbStandardSectorPrefix is\n'recommended' then add a '/T'\nsuffix to the prefix; if\n'guideline' add a '/Z' to suggix
note bottom of GbStandardProfessionalPrefix: ZB_categorycode example:\nZBA is general, ZBB is\nagricultural, ZBC is medical,\netc.
note bottom of GbStandardLocalPrefix: Format: "DBXX YYYY-ZZZZ"\n- XX 2 characters\nlocation code,see note\non prefix list\n- YYYY, 4 or more\ncharacters document identifier\n- ZZZZ, 4 characters year
note bottom of GbStandardEnterprisePrefix: Format: "Q/XXX YYYY-ZZZZ"\n- XXX 3 (or more) characters\nenterprise identified (any characters)\n- YYYY = 4 characters\ndocument code\n- ZZZZ = 4 characters year
note bottom of GbStandardSocialPrefix: Format: "T/XXX YYYY-ZZZZ"\n- XXX 3 characters\social-group identifier (any\ncharacters, e.g. ABC)\n- YYYY = 4 characters document code\n- ZZZZ = 4 characters year

'******* CLASS RELATIONS **********************************************
GbStandardPrefix <|-- GbStandardNationalPrefix
GbStandardPrefix <|-- GbStandardSectorPrefix
GbStandardPrefix <|-- GbStandardProfessionalPrefix
GbStandardPrefix <|-- GbStandardLocalPrefix
GbStandardPrefix <|-- GbStandardEnterprisePrefix
GbStandardPrefix <|-- GbStandardSocialPrefix

@enduml